notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      language: python
      install:
        - true
      script:
        - ./make/manylinux1/build_wheels.sh
    - os: osx
      osx_image: xcode9.3
      language: generic
      install:
        - ./make/osx/install_python.sh
      script:
        - ./make/osx/build_wheels.sh
